### ISSUE TITLE
[13:28:43] [NdMngr-1]  [WRN] spamming thread paused remotely by ISF website

### ISSUE THREAD

**Issue by PJanisio** [mikrohash/isf-jclient#11]
Hi, 

Already started java spammer. And received this message.

`[13:28:43] [NdMngr-1]  [WRN] spamming thread paused remotely by ISF website`

Can you please check ?

Debian OS.

**Comment by vuapo-eth** [comment]
Hi, this is a feature not a bug :smile:

We implemented a way to remotely pause spammers in case the tangle network is congested. Because of recent issues with the confirmation rate, we paused all spammers to see how it effects the network.

If something like this happens, usually there will be a short message explaining that when you start the spammer (assuming you started the jar normally, without the `start` parameter). You can just let your spammer run, it will resume spamming as soon as we command it to do so.

**Comment by PJanisio** [comment]
Thanks! Nice feature indeed :)
